### ISSUE TITLE
Huge bug: Session.Abandon does not work

### ISSUE THREAD

**Issue by LordJZ** [dermeister0/LockFreeSessionState#11]
Used with HashTableSessionStateModule.

The buiilt-in System.Web.SessionState.SessionStateModule abandons the session both in EndRequest and ReleaseRequestState events, whichever is raised first. However, LockFreeSessionStateModule only abandons the session in ReleaseRequestState which means abandon simply doesn't work if ReleaseRequestState is not called for whatever reason.

Repro code:

```
        Session.Abandon();
        Response.Redirect(FormsAuthentication.LoginUrl);
```

Expected: Session is abandoned.
Actual: Session is retained, Abandon did not work.

**Comment by dermeister0** [comment]
Fixed.
